 #message("--SET_CMAKE_OPTION_INCLUDED---------->" ${SET_CMAKE_OPTION_INCLUDED})
 #message("--CMAKE_CXX_COMPILER_ID---------->" ${CMAKE_CXX_COMPILER_ID})
 #message("--CMAKE_C_COMPILER_ID---------->" ${CMAKE_C_COMPILER_ID})
if (NOT SET_CMAKE_OPTION_INCLUDED)
    set(SET_CMAKE_OPTION_INCLUDED ON)
    if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_C_COMPILER_ID STREQUAL "GNU")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -g")
        message("--CMAKE_CXX_FLAGS---------->" ${CMAKE_CXX_FLAGS})
        message("--CMAKE_C_FLAGS---------->" ${CMAKE_C_FLAGS})
    endif ()
endif ()